### PR TITLE
Fix 'should use special characters as defined in the UNA header test

### LINKED ISSUE #23: Test 'Parser.write should use special characters as defined in the UNA header' fail
Hi,

On development branch with node 7.2.0, tests suite fail on 'Parser.write should use special characters as defined in the UNA header'.

```bash
> edifact@1.2.7 test /home/christophe/Dev/tdecaluwe/node-edifact
> istanbul cover -i "[^ies]*.js" --include-all-sources jasmine

Started
............F................................

Failures:
1) Parser.write should use special characters as defined in the UNA header
  Message:
    Expected function not to throw, but it threw Error: Cannot close an incomplete message.
  Stack:
    Error: Expected function not to throw, but it threw Error: Cannot close an incomplete message.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:20:46)

45 specs, 1 failure
Finished in 0.035 seconds

=============================================================================
Writing coverage object [/home/christophe/Dev/tdecaluwe/node-edifact/coverage/coverage.json]
Writing coverage reports at [/home/christophe/Dev/tdecaluwe/node-edifact/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 83.02% ( 357/430 )
Branches     : 81.21% ( 134/165 )
Functions    : 72.6% ( 53/73 )
Lines        : 83.02% ( 357/430 )
================================================================================
npm ERR! Test failed.  See above for more details.
```

As I was looking why, I suppose this is because Tokenizer is instantiated before settings configuration from UNA header and take default Configuration settings.

Do you have any idea how to solve this ?

### PR DESCRIPTION
**Pull request by tophsic**
Tokenizer needs to be reinstantiated
Fix #23

### CODE REVIEW

**Comment by tdecaluwe** [comment]
In fact, it is enough to call `configure()` on the tokenizer. The constructor does nearly exactly that, but this should make it clearer to read.

**Comment by tophsic** [comment]
If we call only `configure()`, we got all these errors:

```bash
> edifact@1.2.7 test /home/christophe/Dev/tdecaluwe/node-edifact
> istanbul cover -i "[^ies]*.js" --include-all-sources jasmine

Started
............F..FF.FF.........................

Failures:
1) Parser.write should use special characters as defined in the UNA header
  Message:
    Expected function not to throw, but it threw Error: Cannot close an incomplete message.
  Stack:
    Error: Expected function not to throw, but it threw Error: Cannot close an incomplete message.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:20:46)

2) Parser.write should call onopensegment when starting a new segment
  Message:
    Expected 1 to equal 2.
  Stack:
    Error: Expected 1 to equal 2.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:40:32)

3) Parser.write should call onclosesegment when terminating a segment
  Message:
    Expected 0 to equal 1.
  Stack:
    Error: Expected 0 to equal 1.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:48:32)

4) Parser.write should call onelement when finishing an new component
  Message:
    Expected 1 to equal 2.
  Stack:
    Error: Expected 1 to equal 2.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:68:32)

5) Parser.write should read characters preceded by the release character as data
  Message:
    Expected undefined to equal '?'.
  Stack:
    Error: Expected undefined to equal '?'.
        at Object.<anonymous> (/home/christophe/Dev/tdecaluwe/node-edifact/spec/ParserSpec.js:74:23)

45 specs, 5 failures
Finished in 0.043 seconds
```

I did not analyze why for instance.

**Comment by tdecaluwe** [comment]
~If I replace your fix by `this._tokenizer.configure(this._configuration);` everything works fine over here. All tests pass. Do you have any other changes in place?~

Was running an old version.

**Comment by tdecaluwe** [comment]
I fixed a different bug in the `Tokenizer.configure` method. Calling `configure()` when parsing the UNA should work now. Can you confirm?

**Pull request merged**
